A01V3      20Meet Entries                  Hy-Tek, Ltd               8.0DHy-Tek, Ltd         252-633-517712062021                                    TM41    N21
B11        Selectivo OPEN Dic 2021                                                   Estadio Nacional                    1214202112172021            L       N50
C11          UFROUNIVERSIDAD DE LA FRONTERA    CLUB UFRO                                                                                   CHI               N36
D01        HAURI, MATIAS                               0326200713MM 2004 13 13OV         2:27,94L                                                            N93
D3                             X FFFFFFFFFFFFF                                                                                                               N50
D01        HAURI, MATIAS                               0326200713MM 4001 15 13OV         4:40,53L                                                            N93
D01        HAURI, MATIAS                               0326200713MM 1004 23 13OV         1:06,57L                                                            N93
D01        HAURI, MATIAS                               0326200713MM15001 25 13OV        19:00,67L                                                            N14
D01        LLAUPE, SAYEN                               0112200713FF 2002 14 13OV         2:46,28L                                                            N93
D3                             X FFFFFFFFFFFFF                                                                                                               N50
D01        LLAUPE, SAYEN                               0112200713FF  502 20 13OV           36,59L                                                            N63
D01        LLAUPE, SAYEN                               0112200713FF 2001 24 13OV         2:35,05L                                                            N83
D01        LLAUPE, SAYEN                               0112200713FF 1002 31 13OV         1:18,88L                                                            N93
D01        MUÑOZ, YASSIRA                              0601200515FF  504 10 13OV           36,27L                                                            N74
D3                             X FFFFFFFFFFFFF                                                                                                               N50
D01        MUÑOZ, YASSIRA                              0601200515FF 2002 14 13OV         2:39,25L                                                            N05
D01        MUÑOZ, YASSIRA                              0601200515FF  502 20 13OV           36,16L                                                            N74
D01        MUÑOZ, YASSIRA                              0601200515FF  501 27 13OV             NT                                                              N54
D01        MUÑOZ, YASSIRA                              0601200515FF 1002 31 13OV         1:14,62L                                                            N05
D01        LLAUPE, JANKA                               1009200317FF 4001  4 13OV         5:14,96L                                                            N73
D3                             X FFFFFFFFFFFFF                                                                                                               N50
D01        LLAUPE, JANKA                               1009200317FF 2002 14 13OV         2:38,75L                                                            N83
D01        LLAUPE, JANKA                               1009200317FF  502 20 13OV           33,49L                                                            N43
D01        LLAUPE, JANKA                               1009200317FF 2001 24 13OV             NT                                                              N33
D01        LLAUPE, JANKA                               1009200317FF 1002 31 13OV         1:11,94L                                                            N73
D01        MUÑOZ, JUAN                                 0305200416MM  504  1 13OV           28,64L                                                            N93
D3                             X FFFFFFFFFFFFF                                                                                                               N50
D01        MUÑOZ, JUAN                                 0305200416MM 2002  5 13OV         2:18,75L                                                            N34
D01        MUÑOZ, JUAN                                 0305200416MM 1002 17 13OV         1:02,21L                                                            N34
D01        MUÑOZ, JUAN                                 0305200416MM  501 19 13OV           26,81L                                                            N04
D01        MUÑOZ, JUAN                                 0305200416MM  502 28 13OV           28,56L                                                            N14
Z01        02Successful Build on 12-06-2021  1  1   1   1    23     5    0     0     0                                                                       N36
